### ISSUE TITLE
help with patent list

### ISSUE THREAD

**Issue by navidlilian** [ravijo/Awesome-CV#4]
Hello Ravi,

Sorry to bother you again.
Do you know how I can insert a list of patents into awesome-cv? 

Best
Navid

**Comment by ravijo** [comment]
@navidlilian 

My apologies for the delayed response. There are two ways I can think of:

1. The best is if you can use an existing format such as those used in the "publication" section. For example, you can notice that the "experience" and "education" section uses the same format.
2. This is a difficult way. Consider you have patent info. in a .bib file, you should define a new bib field and a new bib macro. Then you have to write a bibliography driver for the patent class. For example, you can see [here](https://github.com/ravijo/Awesome-CV/blob/e144cf9145617b6c1982ce8efac62f9ca3e3fcc4/awesome-cv.cls#L814-L862), how a macro and driver are defined.

**Comment by ravijo** [comment]
Closing this issue as no further comments have been received. However, feel free to comment if the problem still exists.
